[package]
name = "client"
version = "0.1.0"
authors = ["Alex McArther <acmcarther@gmail.com>"]
build = "build.rs"

[build-dependencies]
serde_codegen = "0.7.9"
itertools = "*"

[dependencies]
lazy_static = "0.2.1"
gaffer_udp = "0.1.2"
itertools = "*"
serde = "0.7.9"
serde_json = "0.7.4"
time = "0.1.35"
gfx = "0.12.0"
cgmath = "0.10"
gfx_device_gl = "*"
gfx_text = "0.12.0"
gfx_window_glutin = "*"
glutin = "0.6.1"
flate2 = "0.2.13"
specs = "0.7.0"

[dependencies.common]
path = "../common"
