[package]
name = "client"
version = "0.1.0"
authors = ["Alex McArther <acmcarther@gmail.com>"]
build = "build.rs"

[build-dependencies]
serde_codegen = "0.7.9"
itertools = "*"

[dependencies]
gaffer_udp = "0.1.2"
itertools = "*"
serde = "0.7.9"
serde_json = "0.7.4"
time = "0.1.35"
gfx = "0.10.1"
cgmath = "0.10"
gfx_device_gl = "0.9"
gfx_app = "*"
gfx_window_glutin = "0.10"
glutin = "0.4.8"
flate2 = "0.2.13"

[dependencies.common]
path = "../common"
