[package]
name = "common"
version = "0.1.0"
authors = ["Alex McArther <acmcarther@gmail.com>"]
build = "build.rs"

[build-dependencies]
serde_codegen = "0.7.9"
itertools = "*"

[dependencies]
gaffer_udp = "0.1.2"
serde = "0.7.9"
serde_json = "0.7.4"
specs = "0.7.0"
