[package]
name = "common"
version = "0.1.0"
authors = ["Alex McArther <acmcarther@gmail.com>"]

[dependencies.ecs]
path = "./ecs"

[dependencies.protocol]
path = "./protocol"

[dependencies.geometry]
path = "./geometry"
