[package]
name = "geometry"
version = "0.1.0"
authors = ["Alex McArther <acmcarther@gmail.com>"]
build = "build.rs"

[build-dependencies]
serde_codegen = "0.7.9"
itertools = "*"

[dependencies]
itertools = "*"
serde = "0.7.9"
serde_json = "0.7.4"
