[package]
name = "prototype2"
version = "0.1.0"
authors = ["Alex McArther <acmcarther@gmail.com>"]

[dependencies.gaffer_udp]
git = "https://github.com/acmcarther/gaffer_udp"
rev = "65f0d2a999a3470fcab34d19cc1a2caee480a63e"

[[bin]]
name = "space_coop"
path = "src/bin.rs"
